kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1 
metadata: 
  name: rufus-hpa
spec: 
  maxReplicas: 10 
  minReplicas: 1 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: rufus-deployment
  metrics: 
  - type: Resource
    resource: 
      name: cpu
      targetAverageUtilization: 60
